# If you only one circle to run on direct commits to master, you can uncomment this out
# and uncomment the filters: *filter-only-master down below too
#
aliases:
 - &filter-only-master
   branches:
     only:
       - master

version: 2
jobs:
  build:
    filters: *filter-only-master  
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

    steps:
      - checkout
      - run: 
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "rafaelnsantos@users.noreply.github.com"
            git config --global user.name "Rafael"
            cd website && yarn install && GIT_USER=$GIT_USER yarn run deploy